### ISSUE TITLE
Handle backslashes and TeX expressions

### ISSUE THREAD

**Issue by flesser** [jlevy/atom-flowmark#11]
I am using Pandoc to convert my Markdown sources to other formats, e.g. LaTeX.

In Pandoc, [a backslash-escaped space is parsed as a nonbreaking space](https://pandoc.org/MANUAL.html#backslash-escapes), so I use that a lot.
When reflowing the text with atom-flowmark however, it tries to escape the apparently "single" backslash and breaks my text (possibly because strict Markdown only allows for ``\`*_{}[]()>#+-.!`` to be escaped).

My input:
```
The maximum speed is 25\ km/h and here are some \*literal asterisks\* and if I want to print a literal backslash \\ I know how to escape it myself.
```

atom-flowmark:
```
The maximum speed is 25\\ km/h and here are some \*literal asterisks\* and if I want to
print a literal backslash \\ I know how to escape it myself.
```

what I actually wanted:
```
The maximum speed is 25\ km/h and here are some \*literal asterisks\* and if I want to
print a literal backslash \\ I know how to escape it myself.
```

**Comment by flesser** [comment]
It also breaks all kind of inlined Tex:
```latex
$\SI{25}{\km\per\hour}$
```
becomes 
```
$\\SI{25}{\\km\\per\\hour}$
```

**Comment by jlevy** [comment]
Yeah, a good point. Generalizing this issue as it seems like a common scenario.

Probably Flowmark should just preserve non-strict Markdown escapes. KaTex is also common so we should not break that. Further thoughts and PRs welcome!

**Comment by jlevy** [comment]
This is now fixed with release https://github.com/jlevy/atom-flowmark/releases/tag/v0.7.1 !
