### ISSUE TITLE
Don't pad tables

### ISSUE THREAD

**Issue by jlevy** [jlevy/atom-flowmark#36]
Or, maybe better, don't pad them if they exceed 100 chars wide.

Really big tables are almost impossible to edit when padded.

**Comment by wooorm** [comment]
You can turn [`paddedTable` ](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify#optionspaddedtable) off, to never add superfluous spaces.

**Comment by jlevy** [comment]
@wooorm _best_ behavior would be to remove padding if any line is over 100 chars wide. But am assuming that's a bit more work?

**Comment by wooorm** [comment]
That is harder because you need to calculate how many columns something would serialize at, and if that’s too much, serialize it differently (which could again serialize it shorter than the limit). So indeed, that’s not very simple

**Comment by jlevy** [comment]
Seems like it needn't be perfect, just deterministic, e.g. count max raw text chars on any line of the table, then use that, which would reduce the circularity problem.

But OK sticking with simple approach for now, included in latest patch release.
