### ISSUE TITLE
Wrapping of numbers and full stop can cause enumerated item (rare)

### ISSUE THREAD

**Issue by jlevy** [jlevy/atom-flowmark#43]
In this example, a Flowmark wrap causes the years to be treated as enumerated list items :(

![image](https://user-images.githubusercontent.com/2058167/79928433-cbf1be80-83f7-11ea-9512-5c78a9eb7518.png)

**Comment by wooorm** [comment]
Fixed in [remark-parse@8.0.2](https://github.com/remarkjs/remark/releases/tag/remark-parse%408.0.2)!
