### ISSUE TITLE
Cleanup option: Move footnotes to follow punctuation

### ISSUE THREAD

**Issue by jlevy** [jlevy/atom-flowmark#60]
In traditional typography, footnotes should trail punctuation (comma, period, semicolon, quote, etc.). But often they are placed before the punctuation in source files.

A special menu item to move footnotes after punctuation would be helpful for enforcing consistency.

```
const TRAILING_PUNCTUATION_REGEX = /^[,.;:’”'"]+/i;
```

**Comment by wooorm** [comment]
here’s how it’s done in genbook, albeit on the final AST where this would work on mdast.
https://github.com/feynmanlabs/genbook/blob/master/lib/hast-util-shift-superscript.js#L17
